using System;
using System.Net;

namespace laget.Exceptions.Abstractions
{
    [Serializable]
    public abstract class BaseException : Exception
    {
        /// <summary>
        /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
        /// </summary>
        public virtual HttpStatusCode StatusCode { get; set; } = HttpStatusCode.InternalServerError;
        public object Details { get; set; }
        public string Instance { get; set; } = null;

        public virtual string Type { get; }

        protected BaseException()
        {
            Type = GetType().Name;
        }

        protected BaseException(string message)
            : base(message)
        {
            Type = GetType().Name;
        }

        protected BaseException(string message, string details)
            : base(message)
        {
            Type = GetType().Name;
            Details = details;
        }


        protected BaseException(string message, Exception ex)
            : base(message, ex)
        {
            Type = GetType().Name;
        }

        public Models.Response Model => new Models.Response
        {
            Type = Type,
            Title = Message,
            Status = (int)StatusCode,
            Details = Details,
            Instance = Instance
        };

        public void SetStatusCode(HttpStatusCode statusCode)
        {
            StatusCode = statusCode;
        }

        public void SetStatusCode(int statusCode)
        {
            StatusCode = (HttpStatusCode)statusCode;
        }
    }
}
