using System;
using System.Net;

namespace laget.Exceptions
{
    [Serializable]
    public class Exception : System.Exception
    {
        /// <summary>
        /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
        /// </summary>
        public virtual HttpStatusCode StatusCode { get; } = HttpStatusCode.InternalServerError;
        public virtual object Details { get; set; } = null;

        public string Type { get; }

        public Exception()
        {
        }

        public Exception(string message)
            : base(message)
        {
            Type = GetType().Name;
        }

        public Exception(string message, System.Exception ex)
            : base(message, ex)
        {
            Type = GetType().Name;
        }
    }
}
